name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.2.0
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          jekyll_env: production
          target_branch: 'gh-pages'
